### ISSUE TITLE
Use with Grails 2.4.4 and Groovy 2.4 can't find the closure

### ISSUE THREAD

**Issue by double16** [alkemist/grails-remote-control#23]
I'm using Grails 2.4.4, a Gradle build with the cradle-grails-plugin, and Groovy 2.4 (non-standard, I know). The remote control plugin is failing because it can't find the closure. I think this is related to http://jira.codehaus.org/browse/GROOVY-5351 because of the closure naming. I see in https://github.com/alkemist/remote-control a commit was made to address this.

Can you release a new remote-control and grails-remote-control to include the fix?

**Comment by alkemist** [comment]
You just need to bump the remote control version to 0.7. This doesn't require a new plugin release.

**Comment by double16** [comment]
I must be doing this wrong. I am using Gradle and the cradle-grails-plugin to build. I added this:

repositories { maven { url "http://dl.bintray.com/alkemist/maven" } }
dependencies {
test("org.grails.plugins:remote-control:1.5") {
    exclude module: "remote-transport-http"
  }
  test(group: 'io.remotecontrol', name: 'remote-core', version: '0.7')
  test(group: 'io.remotecontrol', name: 'remote-transport-http', version: '0.7') {
    exclude module: "servlet-api"
  }
}

I am getting this compile error:
/Users/pdouble/Workspace/hiveboom/buildPlugins/remote-control-1.5/src/groovy/grails/plugin/remotecontrol/RemoteControlServlet.groovy: 24: unable to resolve class groovyx.remote.transport.http.RemoteControlServlet
 @ line 24, column 1.
   class RemoteControlServlet extends groovyx.remote.transport.http.RemoteControlServlet {
   ^

The RemoteControlServlet is in the jar at:
io/remotecontrol/transport/http/RemoteControlServlet.class

The RemoteControl class is at:
io/remotecontrol/groovy/client/RemoteControl.class

The plugin looks for them in the groovyx package.

**Comment by alkemist** [comment]
My mistake. This will require an update to the plugin.

Would you be up for submitting a pull request with the update?

**Comment by double16** [comment]
Sure, I'll give it a shot.

**Comment by double16** [comment]
ETA on when the new plugin will be published?

**Comment by ldaley** [comment]
Will get to this today.

**Comment by ldaley** [comment]
Published as v 2.0
